/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/user-dashboard'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RawMaterialsRouteImport } from './routes/raw-materials'
import { Route as QualityChecksRouteImport } from './routes/quality-checks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as MonthlyTargetRouteImport } from './routes/monthly-target'
import { Route as MaterialTransferRouteImport } from './routes/material-transfer'
import { Route as ManagerOverrideRouteImport } from './routes/manager-override'
import { Route as ManagerDashboardRouteImport } from './routes/manager-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DailyOverviewRouteImport } from './routes/daily-overview'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ActivityStatusRouteImport } from './routes/activity-status'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsRoute = RawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityChecksRoute = QualityChecksRouteImport.update({
  id: '/quality-checks',
  path: '/quality-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyTargetRoute = MonthlyTargetRouteImport.update({
  id: '/monthly-target',
  path: '/monthly-target',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialTransferRoute = MaterialTransferRouteImport.update({
  id: '/material-transfer',
  path: '/material-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerOverrideRoute = ManagerOverrideRouteImport.update({
  id: '/manager-override',
  path: '/manager-override',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager-dashboard',
  path: '/manager-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOverviewRoute = DailyOverviewRouteImport.update({
  id: '/daily-overview',
  path: '/daily-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityStatusRoute = ActivityStatusRouteImport.update({
  id: '/activity-status',
  path: '/activity-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/activity-status': typeof ActivityStatusRoute
  '/branches': typeof BranchesRoute
  '/daily-overview': typeof DailyOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/manager-override': typeof ManagerOverrideRoute
  '/material-transfer': typeof MaterialTransferRoute
  '/monthly-target': typeof MonthlyTargetRoute
  '/processes': typeof ProcessesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/quality-checks': typeof QualityChecksRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/tv': typeof TvRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/activity-status': typeof ActivityStatusRoute
  '/branches': typeof BranchesRoute
  '/daily-overview': typeof DailyOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/manager-override': typeof ManagerOverrideRoute
  '/material-transfer': typeof MaterialTransferRoute
  '/monthly-target': typeof MonthlyTargetRoute
  '/processes': typeof ProcessesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/quality-checks': typeof QualityChecksRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/tv': typeof TvRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/activity-status': typeof ActivityStatusRoute
  '/branches': typeof BranchesRoute
  '/daily-overview': typeof DailyOverviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/manager-override': typeof ManagerOverrideRoute
  '/material-transfer': typeof MaterialTransferRoute
  '/monthly-target': typeof MonthlyTargetRoute
  '/processes': typeof ProcessesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/quality-checks': typeof QualityChecksRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/tv': typeof TvRoute
  '/user-dashboard': typeof UserDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/activity-status'
    | '/branches'
    | '/daily-overview'
    | '/forgot-password'
    | '/history'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/manager-override'
    | '/material-transfer'
    | '/monthly-target'
    | '/processes'
    | '/products'
    | '/profile'
    | '/quality-checks'
    | '/raw-materials'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/tv'
    | '/user-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/activity-status'
    | '/branches'
    | '/daily-overview'
    | '/forgot-password'
    | '/history'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/manager-override'
    | '/material-transfer'
    | '/monthly-target'
    | '/processes'
    | '/products'
    | '/profile'
    | '/quality-checks'
    | '/raw-materials'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/tv'
    | '/user-dashboard'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/activity-status'
    | '/branches'
    | '/daily-overview'
    | '/forgot-password'
    | '/history'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/manager-override'
    | '/material-transfer'
    | '/monthly-target'
    | '/processes'
    | '/products'
    | '/profile'
    | '/quality-checks'
    | '/raw-materials'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/tv'
    | '/user-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  ActivityStatusRoute: typeof ActivityStatusRoute
  BranchesRoute: typeof BranchesRoute
  DailyOverviewRoute: typeof DailyOverviewRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerOverrideRoute: typeof ManagerOverrideRoute
  MaterialTransferRoute: typeof MaterialTransferRoute
  MonthlyTargetRoute: typeof MonthlyTargetRoute
  ProcessesRoute: typeof ProcessesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  QualityChecksRoute: typeof QualityChecksRoute
  RawMaterialsRoute: typeof RawMaterialsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  TvRoute: typeof TvRoute
  UserDashboardRoute: typeof UserDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-dashboard': {
      id: '/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials': {
      id: '/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof RawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-checks': {
      id: '/quality-checks'
      path: '/quality-checks'
      fullPath: '/quality-checks'
      preLoaderRoute: typeof QualityChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-target': {
      id: '/monthly-target'
      path: '/monthly-target'
      fullPath: '/monthly-target'
      preLoaderRoute: typeof MonthlyTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-transfer': {
      id: '/material-transfer'
      path: '/material-transfer'
      fullPath: '/material-transfer'
      preLoaderRoute: typeof MaterialTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-override': {
      id: '/manager-override'
      path: '/manager-override'
      fullPath: '/manager-override'
      preLoaderRoute: typeof ManagerOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-dashboard': {
      id: '/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-overview': {
      id: '/daily-overview'
      path: '/daily-overview'
      fullPath: '/daily-overview'
      preLoaderRoute: typeof DailyOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-status': {
      id: '/activity-status'
      path: '/activity-status'
      fullPath: '/activity-status'
      preLoaderRoute: typeof ActivityStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  ActivityStatusRoute: ActivityStatusRoute,
  BranchesRoute: BranchesRoute,
  DailyOverviewRoute: DailyOverviewRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerOverrideRoute: ManagerOverrideRoute,
  MaterialTransferRoute: MaterialTransferRoute,
  MonthlyTargetRoute: MonthlyTargetRoute,
  ProcessesRoute: ProcessesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  QualityChecksRoute: QualityChecksRoute,
  RawMaterialsRoute: RawMaterialsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  TvRoute: TvRoute,
  UserDashboardRoute: UserDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
